id = "miniprogram-extension"
name = "Miniprogram Extension"
version = "0.0.1"
schema_version = 1
authors = ["Finogeeks"]
description = "Miniprogram extension"
repository = "https://github.com/finogeeks/miniprogram-zed-extension"
